# https://github.com/261497-Full-Stack-1-68/pj-frontend

FROM oven/bun:1.1

WORKDIR /app

# copy dependencies
COPY package.json bun.lock* package-lock.json* yarn.lock* ./

RUN bun install

# copy source code
COPY . .

# generate prisma client
RUN bunx prisma generate

# build with webpack
RUN bun run build

CMD ["bun", "run", "start"]